name: VASC
channels:
  - default
  - conda-forge
dependencies:
  - ipython
  - ipykernel
  - numpy
  - seaborn
  - pandas
  - glob2
  - opencv
  - pyarrow
  - xlrd
  - jupytext
  - ipywidgets
  - ipycanvas
  - nodejs
